Fix Jupyter Lab error (#28) (#29)
Fixes AttributeError: 'Version' object has no attribute 'major' error when running jupyter lab

- Add setuptools to requirements.txt. See
  https://github.com/jupyterlab/jupyterlab/issues/10111
- Add jupyter lab --help to nbval to catch issue
- Remove ipykernel pinning since ipykernel bug has been fixed