switch to install opencv-python-headless to avoid cannot open libGL.so.1 (#2001)
fix error like this：
python -c "import cv2"

...

File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: libGL.so.1: cannot open shared object file: No such file or
directory

Actually, opencv-python is not necessary in this notebook,
opencv-python-headless is more user-friendly

Signed-off-by: abushwang <abushwangs@gmail.com>
Co-authored-by: Aleksandr Mokrov <aleksandr.mokrov@intel.com>